trigger:
  - "pr"

jobs:
  - job: format check
    displayName: Check that the code is formatted
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: .azure-pipelines/install-rust.yml
      parameters:
        rust_version: stable
    - script: cargo fmt --all -- --check
      displayName: "Check formatting"
  - job: testing
    displayName: Check that the code builds and the tests pass
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: .azure-pipelines/install-rust.yml
      parameters:
        rust_version: stable
    - script: cargo test
      displayName: "Run test"
