trigger:
  - "pr"

jobs:
  - job: format_check
    displayName: Check that the code is formatted
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: .azure-pipelines/install-rust.yml
      parameters:
        rust_version: stable
    - script: rustup component add rustfmt
      displayName: "Add rustfmt"
    - script: cargo fmt --all -- --check
      displayName: "Check formatting"
  - job: testing
    displayName: Check that the code builds and the tests pass
    strategy:
      matrix:
        Linux:
          vmImage: ubuntu-16.04
        MacOS:
          vmImage: macOS-10.13
        Windows:
          vmImage: vs2017-win2016
    pool:
      vmImage: $(vmImage)
    steps:
    - template: .azure-pipelines/install-rust.yml
      parameters:
        rust_version: stable
    - script: cargo test
      displayName: "Run test"
